

*   **Rishabh Patil**
*   **SAP : 60009200056**
*   **Div : K/K2**





## Importing required libraries

In [ ]:
import numpy as np
import pandas as pd
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D


In [ ]:
def split_sequence(sequence,steps):
  X,y=list(),list()
  for start in range(len(sequence)):
    end_index = start + steps
    if end_index > len(sequence)-1:
      break
    sequence_x,sequence_y = sequence[start : end_index], sequence[end_index]
    X.append(sequence_x)
    y.append(sequence_y)
  return array(X),array(y)

In [ ]:
df = pd.read_csv("/content/daily-min-temperatures.csv")
df.head()

Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [ ]:
def exp8(col_name):
  raw_sequence = df[col_name]

  # choose number of time steps
  steps=3

  # split into samples
  X,y = split_sequence(raw_sequence,steps)

  print("****************************************************************")
  print('The input sequence on which we will test our CNN Model: ')
  print(raw_sequence)
  print("\n\n****************************************************************")
  print('The features (X) , lagged values of time series , for our CNN Model')
  print(X[:5])
  print("\n\n****************************************************************")
  print('The respective observed values (y) of the sequence for training in CNN Model')
  print(y)
  print("****************************************************************\n\n")
  # Reshape 2D imput data to 3D input data 
  features = 1
  X = X.reshape((X.shape[0], X.shape[1], features))

  print('After reshaping , the shape of the input X ')
  print(X.shape)
  print("\n\n*************************************************")
  print("*************************************************")
  print('The final form of input feature matrix X')
  print(X[:5])
  print("\n\n*************************************************")
  print("*************************************************")
  print('Feature matrix X is ready for input to CNN Model')
  print("*************************************************\n\n")

  # Defining model architecture
  model = Sequential()
  model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(steps,features)))
  model.add(MaxPooling1D(pool_size=2))
  model.add(Flatten())
  model.add(Dense(100, activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='adam', loss='mse')

  # fit model
  model.fit(X,y,epochs=100, verbose=0)

  #predict
  x_input = array(raw_sequence[-steps-1:-1])
  x_input = x_input.reshape((1,steps,features))
  y_pred = model.predict(x_input,verbose=0)
  print("*************************************************")
  print(f"The next predicted value is ")
  print(y_pred)
  print(f"The next true value is ")
  print(raw_sequence.iloc[-1])
  print("*************************************************")

In [ ]:
exp8("Temp")

****************************************************************
The input sequence on which we will test our CNN Model: 
0       20.7
1       17.9
2       18.8
3       14.6
4       15.8
        ... 
3645    14.0
3646    13.6
3647    13.5
3648    15.7
3649    13.0
Name: Temp, Length: 3650, dtype: float64


****************************************************************
The features (X) , lagged values of time series , for our CNN Model
[[20.7 17.9 18.8]
 [17.9 18.8 14.6]
 [18.8 14.6 15.8]
 [14.6 15.8 15.8]
 [15.8 15.8 15.8]]


****************************************************************
The respective observed values (y) of the sequence for training in CNN Model
[14.6 15.8 15.8 ... 13.5 15.7 13. ]
****************************************************************


After reshaping , the shape of the input X 
(3647, 3, 1)


*************************************************
*************************************************
The final form of input feature matrix X
[[[20.7]
  [17.9]
  [